# Уникальное имя вашего Pages-проекта
name = "my-react-pages-app"                                              # :contentReference[oaicite:0]{index=0}

# Дата совместимости API Workers (формат YYYY-MM-DD)
compatibility_date = "2025-05-24"                                        # :contentReference[oaicite:2]{index=2}

# Директория с результатом сборки React (npm run build → ./build)
pages_build_output_dir = "./build"                                       # :contentReference[oaicite:3]{index=3}